source 'https://rubygems.org'

# Fixing gem versions supported by traveling-ruby
gem 'json', '1.8.3'
gem 'nokogiri', '1.6.7.2'
gem 'blockenspiel', '0.4.5'
gem 'eventmachine', '1.2.0.1'
gem 'redcarpet', '3.3.4'
gem 'thin', '1.6.4'
gem 'sqlite3', '1.3.11'
gem 'mysql2', '0.4.4'
gem 'pg', '0.18.4'

gem "pact_broker", "1.9.2"

